---
title: "Modeling in R"
output: html_notebook
---


Load the libraries

```{r}
library(MASS)
library(tidyverse)
library(car)
library(perturb)
library(corpcor)
library(caret)
library(RANN)
library(bnstruct)
library(DMwR)
library(psych)
library(corrplot)
library(broom)
library(gridExtra)
#library(grid)
library(arules)
library(ggrepel)
library(olsrr)
df <- read.csv('Data/data_train2.csv')
```


Model 1 with all variables

```{r}

df <- read.csv('Data/data_train_2.csv')
x_axis1=df[c(1)]

df<-df[ -c(1) ]

row.names(df) <- unlist(x_axis1, use.names=FALSE)
df<-df[row.names(df)!=49,]
x_axis1<-x_axis1[x_axis1!=49,]


df$enginesize <-log(df$enginesize)
df$curbweight<-df$curbweight/df$wheelbase
df$carlength<-df$carlength*df$carwidth
vars <- c( "wheelbase","carlength","carwidth","carheight","curbweight","enginesize","boreratio","stroke","peakrpm","citympg","highwaympg" )
#vars <- c('compressionratio','enginesize','peakrpm')
df <- df %>% 
  mutate_at(vars, scale, scale = FALSE)
avg2 <- function(x) {  
  
  if(x['fueltype']=='gas'){
    return(as.numeric(x['compressionratio'])-8.85)
  }
  else{
    return(as.numeric(x['compressionratio'])-22.06)
  }
  
  
  
  
  }
df$compressionratio<-apply(df,1,avg2)

avg3 <- function(x) {  
  
  if(x['cylindernumber']=='two_three_four'){
    return(as.numeric(x['horsepower'])-90.75)
  }
  if(x['cylindernumber']=='five_six'){
    return(as.numeric(x['horsepower'])-149.514286)
  }
  else{
    return(as.numeric(x['horsepower'])-204.666667)
  }
  
  
  
  
  }

df$citympg<-apply(df,1,avg4)
df$horsepwer=df$horsepower/df$curbweight
mod1 <- lm(formula = log(price) ~ drivewheel + brandName + enginesize + peakrpm + 
    citympg + fuelsystem:compressionratio+horsepwer+aspiration+carbody+stroke+symboling, data = df)
summary(mod1)
```





```{r}
step.model <- stepAIC(mod1, direction = "both",trace = FALSE)
mod1<-step.model
summary(step.model)
mod1<-step.model
```




Lets check residual plots

```{r}




mod1_table <- augment(step.model,df)
head(mod1_table)
row.names(mod1_table) <- unlist(x_axis1, use.names=FALSE)
```




```{r}
ggplot(mod1_table, aes(wheelbase,.std.resid))+geom_point()+geom_smooth()
#ggplot(mod1_table, aes(wheelbase2,.std.resid))+geom_point()+geom_smooth()
ggplot(mod1_table, aes(carlength,.std.resid))+geom_point()+geom_smooth()
ggplot(mod1_table, aes(carwidth,.std.resid))+geom_point()+geom_smooth()
ggplot(mod1_table, aes(carheight,.std.resid))+geom_point()+geom_smooth()
ggplot(mod1_table, aes(curbweight,.std.resid))+geom_point()+geom_smooth()
ggplot(mod1_table, aes(enginesize,.std.resid))+geom_point()+geom_smooth()
ggplot(mod1_table, aes(boreratio,.std.resid))+geom_point()+geom_smooth()
ggplot(mod1_table, aes(stroke,.std.resid))+geom_point()+geom_smooth()
ggplot(mod1_table[mod1_table$fueltype=='gas',], aes(compressionratio,.std.resid))+geom_point()+geom_smooth()
ggplot(mod1_table[mod1_table$fueltype=='diesel',], aes(compressionratio,.std.resid))+geom_point()+geom_smooth()
ggplot(mod1_table, aes(compressionratio,.std.resid))+geom_point()+geom_smooth()
ggplot(mod1_table, aes(horsepower,.std.resid))+geom_point()+geom_smooth()
ggplot(mod1_table, aes(peakrpm,.std.resid))+geom_point()+geom_smooth()
ggplot(mod1_table, aes(citympg,.std.resid))+geom_point()+geom_smooth()
ggplot(mod1_table, aes(highwaympg,.std.resid))+geom_point()+geom_smooth()
```

```{r}
ggplot(mod1_table) +
  aes(x = symboling, y = .std.resid) +
  geom_point()-> p1

ggplot(mod1_table) +
  aes(x = factor(symboling), y = .std.resid) +
  geom_boxplot() +
  geom_smooth(aes(group = 1), se = FALSE) -> p2

grid.arrange(p1, p2, ncol = 2)

ggplot(mod1_table) +
  aes(x = fueltype, y = .std.resid) +
  geom_point() -> p1

ggplot(mod1_table) +
  aes(x = factor(fueltype), y = .std.resid) +
  geom_boxplot() +
  geom_smooth(aes(group = 1), se = FALSE) -> p2

grid.arrange(p1, p2, ncol = 2)


ggplot(mod1_table) +
  aes(x = aspiration, y = .std.resid) +
  geom_point() -> p1

ggplot(mod1_table) +
  aes(x = factor(aspiration), y = .std.resid) +
  geom_boxplot() +
  geom_smooth(aes(group = 1), se = FALSE) -> p2

grid.arrange(p1, p2, ncol = 2)

ggplot(mod1_table) +
  aes(x = doornumber, y = .std.resid) +
  geom_point() -> p1

ggplot(mod1_table) +
  aes(x = factor(doornumber), y = .std.resid) +
  geom_boxplot() +
  geom_smooth(aes(group = 1), se = FALSE) -> p2

grid.arrange(p1, p2, ncol = 2)

ggplot(mod1_table) +
  aes(x = carbody, y = .std.resid) +
  geom_point() -> p1

ggplot(mod1_table) +
  aes(x = factor(carbody), y = .std.resid) +
  geom_boxplot() +
  geom_smooth(aes(group = 1), se = FALSE) -> p2

grid.arrange(p1, p2, ncol = 2)


ggplot(mod1_table) +
  aes(x = drivewheel, y = .std.resid) +
  geom_point() -> p1

ggplot(mod1_table) +
  aes(x = factor(drivewheel), y = .std.resid) +
  geom_boxplot() +
  geom_smooth(aes(group = 1), se = FALSE) -> p2

grid.arrange(p1, p2, ncol = 2)



ggplot(mod1_table) +
  aes(x = enginelocation, y = .std.resid) +
  geom_point() -> p1

ggplot(mod1_table) +
  aes(x = factor(enginelocation), y = .std.resid) +
  geom_boxplot() +
  geom_smooth(aes(group = 1), se = FALSE) -> p2

grid.arrange(p1, p2, ncol = 2)


ggplot(mod1_table) +
  aes(x = enginetype, y = .std.resid) +
  geom_point() -> p1

ggplot(mod1_table) +
  aes(x = factor(enginetype), y = .std.resid) +
  geom_boxplot() +
  geom_smooth(aes(group = 1), se = FALSE) -> p2

grid.arrange(p1, p2, ncol = 2)


ggplot(mod1_table) +
  aes(x = cylindernumber, y = .std.resid) +
  geom_point() -> p1

ggplot(mod1_table) +
  aes(x = factor(cylindernumber), y = .std.resid) +
  geom_boxplot() +
  geom_smooth(aes(group = 1), se = FALSE) -> p2

grid.arrange(p1, p2, ncol = 2)

ggplot(mod1_table) +
  aes(x = fuelsystem, y = .std.resid) +
  geom_point() -> p1

ggplot(mod1_table) +
  aes(x = factor(fuelsystem), y = .std.resid) +
  geom_boxplot() +
  geom_smooth(aes(group = 1), se = FALSE) -> p2

grid.arrange(p1, p2, ncol = 2)

ggplot(mod1_table) +
  aes(x = brandName, y = .std.resid) +
  geom_point() -> p1

ggplot(mod1_table) +
  aes(x = factor(brandName), y = .std.resid) +
  geom_boxplot() +
  geom_smooth(aes(group = 1), se = FALSE) -> p2

grid.arrange(p1, p2, ncol = 2)
```




```{r}
ggplot(mod1_table, aes(cut(wheelbase,breaks=20),.std.resid,group=cut(wheelbase,breaks=20)))+geom_boxplot()
ggplot(mod1_table, aes(cut(carlength,breaks=20),.std.resid,group=cut(carlength,breaks=20)))+geom_boxplot()
ggplot(mod1_table, aes(cut(carwidth,breaks=20),.std.resid,group=cut(carwidth,breaks=20)))+geom_boxplot()
ggplot(mod1_table, aes(cut(carheight,breaks=20),.std.resid,group=cut(carheight,breaks=20)))+geom_boxplot()
ggplot(mod1_table, aes(cut(curbweight,breaks=20),.std.resid,group=cut(curbweight,breaks=20)))+geom_boxplot()
ggplot(mod1_table, aes(cut(enginesize,breaks=20),.std.resid,group=cut(enginesize,breaks=20)))+geom_boxplot()
ggplot(mod1_table, aes(cut(boreratio,breaks=20),.std.resid,group=cut(boreratio,breaks=20)))+geom_boxplot()
ggplot(mod1_table, aes(cut(stroke,breaks=20),.std.resid,group=cut(stroke,breaks=20)))+geom_boxplot()
ggplot(mod1_table, aes(cut(compressionratio,breaks=20),.std.resid,group=cut(compressionratio,breaks=20)))+geom_boxplot()
ggplot(mod1_table, aes(cut(horsepower,breaks=20),.std.resid,group=cut(horsepower,breaks=20)))+geom_boxplot()
ggplot(mod1_table, aes(cut(peakrpm,breaks=20),.std.resid,group=cut(peakrpm,breaks=20)))+geom_boxplot()
ggplot(mod1_table, aes(cut(citympg,breaks=20),.std.resid,group=cut(citympg,breaks=20)))+geom_boxplot()
ggplot(mod1_table, aes(cut(highwaympg,breaks=20),.std.resid,group=cut(highwaympg,breaks=20)))+geom_point()
```

```{r}

ggplot(mod1_table, aes(wheelbase,.std.resid))+geom_quantile()
ggplot(mod1_table, aes(carlength,.std.resid))+geom_quantile()
ggplot(mod1_table, aes(carwidth,.std.resid))+geom_quantile()
ggplot(mod1_table, aes(carheight,.std.resid))+geom_quantile()
ggplot(mod1_table, aes(curbweight,.std.resid))+geom_quantile()
ggplot(mod1_table, aes(enginesize,.std.resid))+geom_quantile()
ggplot(mod1_table, aes(boreratio,.std.resid))+geom_quantile()
ggplot(mod1_table, aes(stroke,.std.resid))+geom_quantile()
ggplot(mod1_table, aes(compressionratio,.std.resid))+geom_quantile()
ggplot(mod1_table, aes(horsepower,.std.resid))+geom_quantile()
ggplot(mod1_table, aes(peakrpm,.std.resid))+geom_quantile()
ggplot(mod1_table, aes(citympg,.std.resid))+geom_quantile()
ggplot(mod1_table, aes(highwaympg,.std.resid))+geom_quantile()
```

```{r, fig.width = 20, fig.height = 5}
mod1_table['index']<-x_axis1
ggplot(mod1_table) +
  geom_label(aes(x = index, 
                      y = .cooksd, 
                      label = index))
ggplot(mod1_table) +
  geom_text_repel(aes(x = index, 
                      y = .cooksd, 
                      label = index))
```


```{r}
summary1<-summary(mod1)
p<-summary1$fstatistic['numdf']
mod1_table['potential_function']<-mod1_table['.hat']/(1-mod1_table['.hat'])
mod1_table[mod1_table['index']==65,]
```
```{r}
mod1_table[mod1_table['.hat']==1,]
```


```{r}
pot_res <- ols_plot_resid_pot(mod1)
ggplot(pot_res$data) +
  geom_label(aes(x = res, 
                      y = pot, 
                      label = row.names(pot_res$data)))

ggplot(pot_res$data) +
  geom_text_repel(aes(x = res, 
                      y = pot, 
                      label = row.names(pot_res$data)))
```
 
```{r}
ols_plot_dffits(mod1)
```



```{r}
cld=colldiag(model.matrix(step.model),add.intercept = FALSE)
View(round(cld$pi,2))
print(cld$condindx)
```


```{r}
# Only center a subset
vars <- colnames(df)[12:25]

df %>% 
  mutate_at(vars, scale, scale = FALSE)
```

```{r}
vif(step.model)
```







